/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import guitar.domain.Guitar;
import guitar.domain.GuitarSpec;

import static org.junit.Assert.*;

public class domainTest {
    @Test
    public void SpecTest() {
		Guitar Guitar1=new Guitar("001", 1499.95,new GuitarSpec("Collings", "CJ", "acoustic", 12, "Indian Rosewood", "Sitka")); 
		Guitar Guitar2=new Guitar("002", 1499.95,new GuitarSpec("Collings", "CJ", "acoustic", 12, "Indian Rosewood", "Sitka")); 
		System.out.println(Guitar1.getSpec().matches(Guitar2.getSpec()));
    }
}
